language: python
python:
    - "3.6"
sudo: false
notifications:
  email: false
  slack:
    secure: Ddaan9hiJ3x1y5M2RQ9iWBCgS64iaGLehEtZaWa8ySmw0UrxyCDWNIvANFvEUtbUJDZDNde8s+sVmByzVCXxS3RnIm4cwgDNSTZ4u8GSnrLp/4J1SD1/WblFrx7hXqCtZ/z6hNoPUMGzv1/H/Y/CaR4QxiSm2TmUInIsGWdOmDQ3v4D/+X1hEfZwr83X1jSMrwoOLsua7q7bx9O8I0uxFl/9GVcUCGmesWYbgMjzkCird7zxIiwDtIiSaX/P9PXKARn9ci91sPwJGXuLixmfDfK7KGEuIvfEaD6Ag34ZrdVP+MUY+5mPUibj6A4xBzrdIQ6UbBavhkUmGXU5edPVwxoXUOPOAXf4XDp1iayT6G50g2Na5GZ9xPy1k7PrbpImxYZ5avI97f15WtzM/niO0EcFkxJ8OBrEcmtQqphW4qapphLAQpo1oyHF5KQ2+QCDFPHPVSTW28mZamdLPWGUqM7yJfu+CfP3BbnGOIrx6eN2e8m3Yfroioin5q+cDvrVsgTRYdnJzYBb2r2BMsMabrxm3ul/1ReAVXmoglLv4BZmUbsf4mA84GWdDV5WABymVaFsru5Du57gcic8Mf+fSP+SSzGQAF+VRz4+VzgtkaMo2dKtveIdNnjpRA0Bp/nAiB0M/WkJJZy20sBONHBMgwremMcBcIz2T3zJnF0ym2g=
    on_success: change
    on_failure: always
