language: python
python:
- '3.6'
sudo: false
script:
- pip install -e .
- pytest
notifications:
  email: false
  slack:
    on_success: changed
    on_failure: always
    secure: DFSJyzNTam0soAB/5W7/97EVKdQ1LvUkZQf2rIPSsbr4oh7XoL7nKE9Xd8BReRgCmCJK+/84zXeN0dXHtT2irHYx9BaSHQgMvTDIBOOEeMI+hHTtPiTVUC0ZwCSgvmzbAq4s4fNrHqs7rpt/JUpNsdi29O5RdDQZwTwKb74ORAd7bDOosWtRI6JfvgQYgVr0Ox9B0058W2lJ/a+7J4ma3S7FU4EknTd7BiQmATim5z40fhkll4ke8BxYnidWQfjvENh6POzm3/S4l6BvrMuwZEIM22Vij8WPRdCj+OdVezlh4h+mmnqEzKA803R/EvV4Qwx9r0PlS0Dvygmy1T8tbpt41wSIsElcmxCZpAM1z1BnqMclBt/VV9OKAmS2qHqMZ94AGtf9kRGArWpSUELKlXdLyWdZSYnwe3rgpcYEnh7XvBN/oKX63kSRAk0Dsso7oEs+EK1hSuUJj4+7Owo1g+hAb60fnXuOEKnJRNKZ8EvlM0ynQk4Rq7qnIF7DjG7cKxX/tzGjXRtMZ2AQDJmsbC7CKJxdXEVwXfuHgtYk6BlxYQx+Y4VgxkQiUSqUQQjqzdoTsSUu10VC4fgKn28xbe94ccbuzvOqTbEH3o23m9Ci86cOgBgFgBBQDu/i/JTVEDzOfxekgx2XcKUe20GCkaDSeeOKuAONvhBu7syOw5o=
